# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -o discord_pterodactyl_connector-linux-amd64
      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -o discord_pterodactyl_connector-windows-amd64.exe
      - name: Build macOS binary
        run: GOOS=darwin GOARCH=amd64 go build -o discord_pterodactyl_connector-darwin-amd64
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            discord_pterodactyl_connector-linux-amd64
            discord_pterodactyl_connector-windows-amd64.exe
            discord_pterodactyl_connector-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
